### PR TITLE
Fixes for node v0.11 tests.

### LINKED ISSUE #149: Tests don't run on node 0.11.
The tests wont run on travis for node v.011 [because of reasons](https://github.com/tmpvar/jsdom/issues/894) in `jsdom`.`jsdom` is required by `jquery` so I suggest removing `jquery` in favor of `cheerio`.

I'll try to tackle this soon as I like tests to run green and this is a rock in the road of that milestone of mine.

### PR DESCRIPTION
**Pull request by koddsson**
When you cannot sleep, make software.

This deprcates `node-jquery` for `cheerio`. No need to have both and `node-jquery` relies on jsdom which doesn't have a node v0.11 package.

Fixes #149.

### CODE REVIEW

File: endpoints/flight/index.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 var request = require('request'),
-	$ = require('jquery'),
 	h = require('apis-helpers'),
-	app = require('../../server');
+	app = require('../../server'),
+    cheerio = require('cheerio');
```
Comment (koddsson) [inline endpoints/flight/index.js]: This looks funky.

File: endpoints/sports/index.js [hunk 2]
```diff
@@ -101,8 +97,10 @@ app.get('/sports/handball', function (req, res) {
         return res.json(500, {error:'www.hsi.is refuses to respond or give back data'});
       }
 
+      var $;
```
Comment (koddsson) [inline endpoints/sports/index.js]: This is unnecessary.

File: package.json [hunk 3]
```diff
@@ -42,8 +42,6 @@
     "moment": "~2.1.0",
     "xml2js": "~0.2.8",
     "request": "~2.27.0",
-    "scraper": "0.0.9",
```
Comment (koddsson) [inline package.json]: Scraper did seem to be used anywhere so I removed it.

**Comment by koddsson** [comment]
Failing because the tests are flaky! They run now for node v0.11 so this has been accomplished.
